### ISSUE TITLE
'Hiking trails in map' does not update on map move

### ISSUE THREAD

**Issue by hobpet** [RolandMostoha/HuKi-Android#1]
When you open the **Hiking trails in map** panel and move the map to another region, this panel is kept open but does not update, hence the information is not in sync with the visible map area. Either the panel should be closed upon map move or the content should be updated.

![Sample screen with the error](https://i.imgur.com/KrRkgYk.jpg)

**Comment by RolandMostoha** [comment]
Fixed in: https://github.com/RolandMostoha/HuKi-Android/commit/15aca6a2d461b9564f3ed63476ebd0ac13ceab14
